### ISSUE TITLE
Authentication Failed to AC

### ISSUE THREAD

**Issue by marcoahp** [liaan/broadlink_ac_mqtt#100] opened 2022-09-23 08:43 UTC
I get this log:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun broadlink-ac-mqtt (no readiness notification)
s6-rc: info: service legacy-services successfully started
Starting Monitor...
Authentication Failed to AC
__init__() should return None, not 'bool'
Stopping
Starting Monitor...
Authentication Failed to AC
__init__() should return None, not 'bool'
Stopping
Starting Monitor...
Authentication Failed to AC
__init__() should return None, not 'bool'
Stopping
Starting Monitor...
Authentication Failed to AC
__init__() should return None, not 'bool'
Stopping
Starting Monitor...
Authentication Failed to AC
__init__() should return None, not 'bool'
Stopping
Starting Monitor...
Authentication Failed to AC
__init__() should return None, not 'bool'
Stopping
Starting Monitor...
Authentication Failed to AC
__init__() should return None, not 'bool'
Stopping

**Comment by LordDethman** [comment] 2022-09-23 16:09
I had a similar problem with mine when I set them up long ago. What was found from several others and myself is dont finish the setup on whatever app is being used. 

Go through the setup only far enough to get it on the WiFi then close the app. If you go through the whole setup and register with the "online" services it changes the default password in the unit.

Hope that helps.

**Comment by liaan** [comment] 2022-09-26 05:02
did anyone ever try capture the "new password" ? maybe one can update it in the code one day?

**Comment by marcoahp** [comment] 2022-10-07 11:32
How could I capture the new password? I would do it for you

**Comment by marcoahp** [comment] 2022-10-07 11:34
> I had a similar problem with mine when I set them up long ago. What was found from several others and myself is dont finish the setup on whatever app is being used.
> 
> Go through the setup only far enough to get it on the WiFi then close the app. If you go through the whole setup and register with the "online" services it changes the default password in the unit.
> 
> Hope that helps.

So, do I have to lose the AcFreedom integration? This is not a option because I use some options not available in the HA integration.

**Comment by liaan** [comment] 2023-01-23 06:18
going to close this

we all know now what the problem is, and so far no workaround unless you use the cloud based comms, which this service don't do yet.

**Closed as completed by liaan** 2023-01-23 06:18 UTC
